const sources= [
{"topic":"agri","label":"International Food Policy Research Institute","href":"http://library.ifpri.info/open-data/","desc":"IFPRI has developed applications built around open data from its own and external sources to promote understanding of food security issues.",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"agri","label":"World Food Program","href":"http://www.wfp.org/food-security/assessments/emergency-food-security-assessment","desc":"Targeted interventions are needed to help to improve the lives of the poorest people - people who, either permanently or during crisis periods, are unable to produce enough food...",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"agri","label":"UN FAOSTAT","href":"http://www.fao.org/faostat/en/#home","desc":"The United Nations Food and Agriculture Organization provides free access to food and agriculture data for over 245 countries and territories and covers all FAO regional groupings from 1961 to the most recent year available.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"biol","label":"IGSR: The International Genome Sample Resource","href":"http://www.internationalgenome.org/home","desc":"The 1000 Genomes Project ran between 2008 and 2015, creating the largest public catalogue of human variation and genotype data. As the project ended, the Data Coordination Centre at EMBL-EBI has received continued funding from the Wellcome Trust to maintain and expand the resource.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"biol","label":"biosharing.org","href":"https://biosharing.org/","desc":"A curated, informative and educational resource on inter-related data standards, databases, and policies in the life, environmental and biomedical sciences",download:true,gis:false,explorer:true,chart:true,tools:false,resource:true},
{"topic":"child","label":"Kids Count","href":"http://datacenter.kidscount.org/","desc":"KIDS COUNT is a project of the Annie E. Casey Foundation to track the well-being of children in the United States.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"child","label":"Child Trends","href":"http://www.childtrends.org/databank-indicators/","desc":"Child Trends is the nation’s leading nonprofit research organization focused exclusively on improving the lives and prospects of children, youth, and their families.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"climate","label":"IRI/LDEO Climate Data Library","href":"http://iridl.ldeo.columbia.edu/","desc":"The IRI Data Library is a powerful and freely accessible online data repository and analysis tool that allows a user to view, analyze, and download hundreds of terabytes of climate-related data through a standard web browser.",download:true,gis:true,explorer:true,chart:true,tools:true,resource:true},
{"topic":"crim","label":"Fatal Force","href":"https://www.washingtonpost.com/graphics/national/police-shootings-2016/","desc":"955 people have been shot and killed by police in 2016. This database is based on news reports, public records, social media and other sources. Read about our methodology. Download the data. See the 2016 database.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"crime","label":"Crime Mapping","href":"http://www.crimemapping.com/","desc":"CrimeMapping.com has been developed by TriTech Software Systems to help law enforcement agencies throughout North America provide the public with valuable information about recent crime activity in their neighborhood. Our goal is to assist police departments in reducing crime through a better-informed citizenry.",download:false,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"crime","label":"Southern Poverty Law Center","href":"https://www.splcenter.org/","desc":"We monitor hate groups and other extremists throughout the United States and expose their activities to the public, the media and law enforcement.  They provide a \Hate Map\ and other graphics.", download:false,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"crime","label":"Hall of Justice","href":"http://hallofjustice.sunlightfoundation.com/","desc":"Hall of Justice, a project of the Sunlight Foundation, is a robust, searchable inventory of publicly available criminal justice datasets and research.  While not comprehensive, Hall of Justice contains nearly 10,000 datasets on topics like corrections, recidivism, guns, police encounters, etc.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"crime","label":"Sourcebook of US Criminal Justice Statistics","href":"http://www.albany.edu/sourcebook/","desc":"Comprehensive source of data, includes public opinion polls.", download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"econ","label":"Measuring Worth","href":"https://measuringworth.com/aboutus.php","desc":"Measuring Worth is a service for calculating relative worth over time.  There are two missions: 1) make available to the public the highest quality and most reliable historical data on important economic aggregates 2) to provide carefully designed comparators (using these data) that explain the many issues involved in making value comparisons over time.",download:true,gis:false,explorer:true,chart:true,tools:true,resource:false},
{"topic":"econ","label":"State of Working America","href":"http://stateofworkingamerica.org/","desc":"The Data Library provides researchers, media, and the public with easily accessible, up-to-date, and comprehensive historical data on the American labor force. It is compiled from Economic Policy Institute analysis of government data sources.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"econ","label":"World Wealth & Income Database","href":"http://wid.world/","desc":"The source for global wealth inequality data.  The key novelty has been to combine fiscal, survey and national accounts data in a systematic manner. This allowed us to compute longer and more reliable top income shares series than previous inequality databases (which generally rely on self-reported survey data, with large under-reporting problems at the top, and limited time span). These series had a large impact on the global inequality debate.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"econ","label":"Penn World Tables","href":"http://www.rug.nl/ggdc/productivity/pwt/","desc":"Penn World Tables version 9.0 is a database with information on relative levels of income, output, input and productivity, covering 182 countries between 1950 and 2014.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"econ","label":"FRED","href":"https://fred.stlouisfed.org/","desc":"The Research Division of the Federal Reserve Bank of St. Louis is responsible for advising the Bank president on matters of economic policy. The Division monitors the economic and financial literature and produces research in the areas of money and banking, macroeconomics, and international and regional economics.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"econ","label":"geoFRED","href":"https://geofred.stlouisfed.org/","desc":"GeoFRED® allows you to create, customize, and share geographical maps of data found in FRED®. Easily access the details and adjust how the data are displayed. You can also transform the data and download it according to geographic category and time frame.",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"econ","label":"Economic Freedom - the Heritage Foundation","href":"http://www.heritage.org/index/explore","desc":"Today, we live in the most prosperous time in human history. Poverty, sicknesses, and ignorance are receding throughout the world, due in large part to the advance of economic freedom. I",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"econ","label":"Economic Freedom - the Fraser Institute","href":"http://www.freetheworld.com/datasets_efw.html","desc":"Our annual report, Economic Freedom of the World, uses 42 distinct pieces of data to measure economic freedom in 157 nations.  This site also links to The Economic Freedom of the World index data.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"econbusi","label":"Global Edge","href":"http://globaledge.msu.edu/tools-and-data","desc":"Michigan State University tool to help companies compare Emerging Markets across several dimensions.  Requires creation of free account.",download:true,gis:true,explorer:true,chart:true,tools:true,resource:true},
{"topic":"econbusi","label":"Kilts Center - Marketing Databases","href":"https://research.chicagobooth.edu/kilts/marketing-databases","desc":"The Kilts Center at the University of Chicago makes two datasets, Neilsen's television viewing and sales store data available at no charge for academic research.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"econbusi","label":"Industry Statistics Portal","href":"http://www.census.gov/econ/isp/","desc":"Census Bureau application that searches across programs that provide economic data for a user-selected industry. To choose the industry you are interested in use the NAICS code or keyword.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"econmega","label":"World Bank","href":"http://data.worldbank.org/","desc":"The World Bank's Open Data initiative is intended to provide all users with access to World Bank data. The data catalog is a listing of available World Bank datasets, including databases, pre-formatted tables, reports, and other resources.",download:true,gis:true,explorer:true,chart:true,tools:true,resource:true},
{"topic":"econmega","label":"OECD data","href":"https://data.oecd.org/","desc":"The OECD provides a forum in which governments can work together to share experiences and seek solutions to common problems. We work with governments to understand what drives economic, social and environmental change. We measure productivity and global flows of trade and investment. We analyse and compare data to predict future trends. We set international standards on a wide range of things, from agriculture and tax to the safety of chemicals.",download:true,gis:true,explorer:true,chart:true,tools:true,resource:true},
{"topic":"econmega","label":"International Monetary Fund","href":"http://www.imf.org/external/datamapper/","desc":"The International Monetary Fund (IMF) is an organization of 189 countries, working to foster global monetary cooperation, secure financial stability, facilitate international trade, promote high employment and sustainable economic growth, and reduce poverty around the world.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"real","label":"Real Estate Existing Home Sales by State (NAR)","href":"http://economistsoutlook.blogs.realtor.org/2015/08/24/existing-home-sales-data-by-state/","desc":"This information is typically raw counts of sales from local multiple listing services (MLSs) though availability and format of the data varies.  A list of state data providers, which includes association and non-association providers, is given as a courtesy reference.  ",download:true,gis:false,explorer:false,chart:true,tools:false,resource:false},
{"topic":"real","label":"National Association of Realtors Data &amp; Statistics","href":"https://www.nar.realtor/research-and-statistics","desc":"NAR's annual survey of recent home buyers and sellers provides insight into what people are buying and selling and why.",download:true,gis:false,explorer:false,chart:true,tools:false,resource:false},
{"topic":"econtra","label":"UNCTAD","href":"http://unctadstat.unctad.org/EN/","desc":"UNCTAD produces more than 150 indicators and statistical time series essential for the analysis of: International trade, economic trends, foreign direct investment, external financial resources, population and labor force, commodities, information economy, creative economy and maritime transport.\n",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"econtra","label":"Financial Tracking Service","href":"https://ftsbeta.unocha.org/","desc":"FTS is managed by the UN Office for the Coordination of Humanitarian Affairs (OCHA).  It is a centralized source of curated, continuously updated, fully downloadable data and information on humanitarian funding flows.",download:false,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"edu","label":"Academy Data Forum","href":"https://www.amacad.org/content/research/dataForumList.aspx","desc":"The Data Forum provides a neutral space for Academy Fellows, guest writers, and staff to discuss the data that informs all of the Academy's program areas: the Humanities, Arts, and Education; Science, Engineering and Technology; Global Security and International Affairs; and American Institutions and the Public Good.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"edu","label":"Humanities Indicator","href":"http://humanitiesindicators.org/","desc":"Using Data to Make a Strong Case for the Humanities.",download:true,gis:false,explorer:false,chart:true,tools:false,resource:false},
{"topic":"edu","label":"GRID","href":"https://grid.ac/institutes","desc":"Global Research Identifier Database. Cataloging the world's research organisations.",download:true,gis:true,explorer:false,chart:true,tools:false,resource:false},
{"topic":"ener","label":"International Energy Statistics","href":"http://www.iea.org/statistics/","desc":"The IEA was founded in 1974 to help countries co-ordinate a collective response to major disruptions in the supply of oil. While this remains a key aspect of its work, the IEA has evolved and expanded. It is at the heart of global dialogue on energy, providing authoritative statistics and analysis. ",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"healins","label":"HIX Compare 2015-2017 Datasets","href":"http://www.rwjf.org/en/library/research/2015/12/hix-compare-2015-2017-datasets.html","desc":"This unique dataset compares information on premiums, deductibles and out-of-pocket maximums, as well as cost-sharing requirements for primary care and specialist visits, prescription drugs, emergency room services and inpatient and outpatient visits for all plans across all 50 states.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"ener","label":"DOE Data Explorer","href":"http://www.osti.gov/dataexplorer/","desc":"Discover science, technology, engineering research and data collections from the US Department of Energy",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"env","label":"International Disasters Database","href":"http://www.emdat.be/database","desc":"EM-DAT is a global database on natural and technological disasters, containing essential core data on the occurrence and effects of more than 21,000 disasters in the world, from 1900 to present.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"govt","label":"Open Secrets","href":"http://www.opensecrets.org/news/","desc":"Nonpartisan, independent and nonprofit, the Center for Responsive Politics is the nations premier research group tracking money in U.S. politics and its effect on elections and public policy and our mission is to use that knowledge to strengthen our democracy. ",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"govt","label":"Congressional Tax Reform Tracker","href":"http://taxfoundation.org/comparing-congressional-tax-plans","desc":"It has been more than 30 years since the last major overhaul of the U.S. federal tax code and many lawmakers are getting restless. Use this tool to compare proposals.",download:true,gis:false,explorer:false,chart:true,tools:false,resource:false},
{"topic":"govt","label":"Discover US Government Information","href":"https://www.govinfo.gov/","desc":"Megasite alert!  Massive new front end to the US government.",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"govt","label":"US Politics and Policy","href":"http://www.people-press.org/category/datasets/","desc":"Pew Research Center is a nonpartisan fact tank that informs the public about the issues, attitudes and trends shaping America and the world. We conduct public opinion polling, demographic research, content analysis and other data-driven social science research. We do not take policy positions.",download:false,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"health","label":"Milliman Medical Index","href":"http://us.milliman.com/mmi/","desc":"Milliman Medical Index is an actuarial analysis of the projected total cost of healthcare for a hypothetical family of four covered by an employer-sponsored preferred provider organization (PPO) plan.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"health","label":"AIDSinfo Online database","href":"http://www.aidsinfoonline.org/devinfo/libraries/aspx/Home.aspx","desc":"This database contains country-reported GARPR data and Spectrum estimates (unrounded version for graphing purposes). For official figures, please visit http://aidsinfo.unaids.org.",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"health","label":"State Health Facts - Kaiser Foundation","href":"http://kff.org/statedata/","desc":"The Hery J. Kaiser Foundation has a range of data pertaining to health care policy, women, minorities, the ACA, medicare and medicaid.  They also provide a news service and conduct public opinion polls.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"health","label":"WHO Global Health Observatory","href":"http://www.who.int/gho/en/","desc":"The portal features the latest data on access to health services globally and in each of WHO’s 194 Member States, along with information about equity of access. Next year WHO will add data on the impact that paying for health services has on household finances. ",download:true,gis:false,explorer:false,chart:true,tools:false,resource:false},
{"topic":"healins","label":"Reform by the Numbers","href":"http://www.rwjf.org/en/library/features/reform-by-the-numbers.html","desc":"The Robert Wood Johnson Foundation is taking a close look at The Affordable Care Act.  They also have a data archive hosted at ICPSR.",download:true,gis:false,explorer:false,chart:true,tools:false,resource:false},
{"topic":"healins","label":"Dental Plans Dataset","href":"http://www.rwjf.org/en/library/research/2015/11/dental-plans-dataset.html","desc":"This Dental Plans Dataset tracks a number of issues concerning dental plans sold on the marketplaces and access to dental care for underserved populations for every U.S. state.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"healins","label":"ProPublica - Medicare Prescriptions","href":"http://projects.propublica.org/checkup/","desc":"Journalism in the public interest: Medicare’s popular prescription-drug program serves 41 million people and pays for more than one of every four prescriptions written nationwide. Use this tool to find and compare doctors and other providers in Part D in 2014.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"history","label":"EH.Net Databases in Economic History","href":"http://eh.net/databases/","desc":"EH.Net provides an on-line location for researchers in economic history to make their data series available to other professionals and interested scholars. Several data series have been given to EH.Net and are available as downloadable files, while many other titles may be accessed through our Database Directory.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"history","label":"Afro-Louisiana History and Genealogy","href":"http://www.ibiblio.org/laslave/fields.php","desc":"datasets are available to download. Example searches include:  African Names-A listing of slaves with African names. Revolts-Slaves involved in a conspiracy or a revolt against slavery. Runaways-Slave involved with reports of runaways, interrogation of captured runaways, and testimony by slaves about runaways.",download:true,gis:false,explorer:true,chart:false,tools:false,resource:false},
{"topic":"history","label":"Medieval and Early Modern Data Bank","href":"http://www2.scc.rutgers.edu/memdb/aboutmemdb.html","desc":"The Medieval and Early Modern Data Bank is a project established to provide scholars with an expanding library of information in electronic format on the medieval and early modern periods of European history, circa 800-1815 C.E.",download:true,gis:false,explorer:true,chart:false,tools:false,resource:false},
{"topic":"history","label":"Digital Humanities Institue- University of Sheffield","href":"https://hridigital.shef.ac.uk/projects/","desc":"one of the UK's leading Digital Humanities teams, providing research and development services for the arts, humanities and heritage domains.",download:false,gis:false,explorer:true,chart:false,tools:false,resource:false},
{"topic":"history","label":"London Lives","href":"https://www.londonlives.org/","desc":"London Lives makes available, in a fully digitised and searchable form, a wide range of primary sources about eighteenth-century London, with a particular focus on plebeian Londoners. This resource is supplemented by fifteen datasets created by other projects.",download:false,gis:false,explorer:true,chart:false,tools:false,resource:false},
{"topic":"history","label":"World Historical Dataverse","href":"https://dataverse.harvard.edu/dataverse/worldhistorical","desc":"Datasets available here were submitted by contributors, retrieved by CHIA staff, or created by linkage of existing datasets. They have been documented systematically according to the CHIA Level 1 standard of documentation.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"history","label":"African American Migrations","href":"http://www.inmotionaame.org/migrations/index.cfm","desc":"In Motion: The African-American Migration Experience presents a new interpretation of African-American history, one that focuses on the self-motivated activities of peoples of African descent to remake themselves and their worlds. ",download: false,gis:false,explorer:true,chart:true,tools:false,resource:true},
{"topic":"internet","label":"ITC Development Index","href":"https://www.itu.int/net4/ITU-D/idi/2016/","desc":"ITU collects ICT statistics for 200 economies and over 100 indicators. Access a large amount of free ICT statistics, including on broadband, Internet use, mobile-cellular and mobile-broadband networks ",download:true,gis:false,explorer:false,chart:true,tools:false,resource:false},
{"topic":"internet","label":"Global Stats Counter","href":"http://gs.statcounter.com/#all-browser-US-monthly-201612-201612-bar","desc":"Internet usage, browsers, operating systems, mobile devices, screen resolutions, etc.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"internet","label":"Computing Research Association","href":"http://datavisualization.cra.org/","desc":"Explore national survey data collected from thousands of computing students annually via the Data Buddies Project.  CERP conducts large scale survey research focusing on patterns of entry and persistence in computing research at the post-secondary level.",download:false,gis:false,explorer:true,chart:false,tools:false,resource:false},
{"topic":"internet","label":"Twitter Streams","href":"https://dev.twitter.com/streaming/overview","desc":"The Twitter Platform connects your website or application with the worldwide conversation happening on Twitter.",download:false,gis:false,explorer:false,chart:false,tools:true,resource:false},
{"topic":"internet","label":"Internet, Science and Tech (Pew)","href":"http://www.pewinternet.org/","desc":"The Pew Research Center's Internet Project is pleased to offer scholars access to raw data sets from our research. All uses of this data should reference the Pew Research Center as the source of the data and acknowledge that the Pew Research bears no responsibility for interpretations presented or conclusions reached based on analysis of the data.",download:true,gis:false,explorer:false,chart:true,tools:false,resource:false},
{"topic":"internet","label":"Click dataset","href":"http://cnets.indiana.edu/groups/nan/webtraffic/click-dataset/","desc":"To foster the study of the structure and dynamics of Web traffic networks, we make available a large dataset (‘Click Dataset’) of about 53.5 billion HTTP requests made by users at Indiana University.  The Click Dataset is large (~2.5 TB compressed), which requires that it be transferred on a physical hard drive. You will have to provide the drive as well as pre-paid return shipment.",download:false,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"internet","label":"CAIDA Centre for Applied Internet Data Analysis","href":"http://www.caida.org","desc":"CAIDA curates datasets resulting from both active and passive measurement of the Internet. We provide access to these datasets for researchers in accordance with University of California, San Diego policy. ",download:true,gis:false,explorer:true,chart:true,tools:true,resource:false},
{"topic":"internet","label":"Broadband Portal (OECD)","href":"http://www.oecd.org/sti/broadband/oecdbroadbandportal.htm#map","desc":"FAQs\nThe OECD broadband portal provides access to a range of broadband-related statistics gathered by the OECD.  Policy makers must examine a range of indicators which reflect the status of individual broadband markets.",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"internet","label":"Child Language Data Exchange System","href":"http://childes.psy.cmu.edu/","desc":"CHILDES is the child language component of the TalkBank system. \nTalkBank is a system for sharing and studying conversational interactions.",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"military","label":"SIPRI databases","href":"https://www.sipri.org/databases","desc":"SIPRI is an independent international institute dedicated to research into conflict, armaments, arms control and disarmament. Established in 1966, SIPRI provides data, analysis and recommendations, based on open sources.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"military","label":"Correlates of War","href":"http://www.correlatesofwar.org/data-sets","desc":"COW seeks to facilitate the collection, dissemination, and use of accurate and reliable quantitative data in international relations. Key principles of the project include a commitment to standard scientific principles of replication, data reliability, documentation, review, and the transparency of data collection procedures. ",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"military","label":"Economic Freedom Institute","href":"http://economicsandpeace.org/research/","desc":"Measuring peace at the global and national level allows us to assess the social, political and economic factors that create peace.  Additional measures are political risk",download:true,gis:false,explorer:true,chart:false,tools:false,resource:false},
{"topic":"military","label":"Global Terrorism database","href":"https://www.start.umd.edu/gtd/","desc":"The Global Terrorism Database (GTD) is an open-source database including information on terrorist events around the world from 1970 through 2015 (with annual updates planned for the future).",download:true,gis:false,explorer:true,chart:false,tools:false,resource:false},
{"topic":"demos","label":"UNHCR The UN Refugee Agency","href":"http://popstats.unhcr.org/en/overview","desc":"UNHCR's populations of concern: asylum seekers, refugees, stateless persons from the year 1951 up to 2015 and more current monthly data in some categories.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"demos","label":"UNICEF Data: Monitoring the Situation of Children and Women","href":"https://data.unicef.org/","desc":"UNICEF supports countries in collecting data related to children and women through Multiple Indicator Cluster Surveys (MICS), an international household survey programme. Since its inception in the mid-1990s, five rounds of MICS have been completed (in 1995-1996, 2000-2001, 2005-2006, 2009-2012, 2013-2015) and a sixth is now under way (2016-2018). ",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"demos","label":"Knowledge Center on Migration and Demography","href":"https://ec.europa.eu/jrc/en/migration-and-demography/knowledge/data","desc":"The target audience of this data catalogue is primarily policy makers and practitioners of migration. The catalogue is intended to answer the question \what data exists already that can be of use to study migration and develop migration policies\. Academics and other experts are encouraged to use the links to the data sources to find more detailed and updated information directly from the data providers themselves.  Includes data on trafficking, smuggling, asylum, refugees, forced displacement, etc.",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"demos","label":"United Nations - World Population Prospects","href":"https://esa.un.org/unpd/wpp/DataQuery/","desc":"The 2015 Revision of World Population Prospects is the twenty-fourth round of official United Nations population estimates and projections that The 2015 Revision of World Population Prospects is the twenty-fourth round of official United Nations population estimates and projections that have been prepared by the Population Division of the Department of Economic and Social Affairs of the United Nations Secretariat. The main results are presented in a series of Excel files displaying key demographic indicators for each development group, income group, major area, region and country for selected periods or dates within 1950-2100 of key demographic indicators for each development group, income group, major area, region and country for selected periods or dates within 1950-2100.",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"demos","label":"IPUMS MPC","href":"https://www.ipums.org/","desc":"The Integrated Public Use Microdata Series (IPUMS-USA) consists of more than fifty high-precision samples of the American population drawn from fifteen federal censuses and from the American Community Surveys of 2000-present.  IPUMS is not a collection of compiled statistics; it is composed of microdata. Each record is a person, with all characteristics numerically coded. In most samples persons are organized into households, making it possible to study the characteristics of people in the context of their families or other co-residents.  Because the data are individuals and not tables, researchers must use a statistical package to analyze the millions of records in the database. A data extraction system enables users to select only the samples and variables they require.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"demos","label":"AARP data explorer","href":"http://dataexplorer.aarp.org/search/topic#","desc":"Founded in 1985, PPI publishes policy analyses and provides updates on a range of topics, including current AARP priorities and emerging issues that will affect older adults in the future.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"demos","label":"UN Population Division","href":"https://esa.un.org/unpd/wpp/DataQuery/","desc":"This interactive data query offers data for selected variables from the medium variant of World Population Prospects: The 2015 Revision.",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"demos","label":"Human Development Report","href":"http://hdr.undp.org/en/data","desc":"In 1990 the first Human Development Report introduced a new approach for advancing human wellbeing. Human development – or the human development approach - is about expanding the richness of human life, rather than simply the richness of the economy in which human beings live. It is an approach that is focused on people and their opportunities and choices.",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"demos","label":"The UN Refugee Agency","href":"http://popstats.unhcr.org/en/overview","desc":"The database currently contains data about UNHCR's populations of concern from the year 1951 up to 2014 and you can use it to investigate different aspects of these populations: their general composition by location of residence or origin, their status (refugees, asylum seekers, internally displaced persons, etc.), their evolution over time, and so on..",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"psych","label":"Personality Tests - raw data","href":"http://personality-testing.info/_rawdata/","desc":"All data is anonymous. Users were informed at the beginning of the test that there answers would be used for research and were asked to confirm that their answers were accurate and suitable for research upon completion (those that did not have been removed from these datasets).",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"psych","label":"Online Psychology Laboratory","href":"http://opl.apa.org/Instructors/DownloadData.aspx","desc":"OPL represents the first National Science Foundation funded entry for psychology in the National Science Digital Library. The APA Education Directorate also provides support for this project. OPL currently offers classic studies in psychology that students can participate in, and then analyze data from the experiences. ",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"sex","label":"Gender and Land Rights Database","href":"http://www.fao.org/gender-landrights-database/data-map/statistics/en/","desc":"The Gender and Land Rights database highlights the major political, legal and cultural factors that influence the realisation of women's land rights throughout the world.  It also serves as a platform to address, discuss and provide information about gender and land issues.",download:true,gis:true,explorer:true,chart:true,tools:false,resource:false},
{"topic":"sex","label":"Family Planning Centers","href":"http://thedataweb.rm.census.gov/TheDataWeb_HotReport2/econsnapshot/2012/snapshot.hrml?NAICS=621410","desc":"An \Industry Snapshot\ from the Census Bureau covering 2008-2013.  It includes locations, payroll, revenue, pop. served, etc.",download:true,gis:true,explorer:false,chart:true,tools:false,resource:false},
{"topic":"sex","label":"LGBT Stats - Williams Institute","href":"http://williamsinstitute.law.ucla.edu/visualization/lgbt-stats/#density","desc":"The Williams Institute (UCLA School of Law) is dedicated to conducting rigorous, independent research on sexual orientation and gender identity law and public policy. The Institute does not appear to gather its own data, rather it uses publicly avaiable sources for policy research.",download:false,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"sex","label":"Social Justice Sexuality","href":"http://socialjusticesexuality.com/","desc":"The Social Justice Sexuality Project is one of the largest ever national surveys of Black, Latina/o, and Asian and Pacific Islander, and multiracial lesbian, gay, bisexual, and transgender (LGBT) people.",download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"sex","label":"Guttmacher Institute","href":"https://data.guttmacher.org/regions","desc":"The Guttmacher Institute is a primary source of research and policy analysis on abortion, contraception, HIV and STIs, pregnancy and teens in the United States and internationally.",download:false,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"sex","label":"CDC - Sexual Health","href":"https://www.cdc.gov/sexualhealth/data.html","desc":"an array of datasets related to sexual health, risk, behavior, etc.", download:true,gis:false,explorer:false,chart:false,tools:false,resource:false},
{"topic":"survey","label":"Survey of Consumers","href":"http://www.sca.isr.umich.edu/","desc":"monthly Index of Consumer Sentiment",download:true,gis:false,explorer:false,chart:true,tools:false,resource:false},
{"topic":"taxes","label":"Tax Foundation","href":"http://taxfoundation.org/data","desc":"Our Tax Data section is designed to provide quick and easy access to a wide range of data on tax rates, collections and overall tax burdens. ",download:true,gis:false,explorer:false,chart:true,tools:false,resource:false},
{"topic":"taxes","label":"Non-profit Explorer","href":"https://projects.propublica.org/nonprofits/","desc":"Use this database to search over 1.8 million tax returns from tax-exempt organizations and see financial details such as their executive compensation and revenue and expenses. You can browse raw IRS data released since 2013 and access over 8.3 million tax filing documents going back as far as 2001.",download:true,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"trans","label":"London Transport Unified API","href":"https://api.tfl.gov.uk/swagger/ui/index.html?url=/swagger/docs/v1#!/BikePoint/BikePoint_GetAll","desc":"See what tube trains are running late.  The London Underground prefers that you register for their API. Data includes accidents, bike points, taxis, air quality, etc.  You can test it out here.",download:false,gis:false,explorer:true,chart:true,tools:false,resource:false},
{"topic":"trans","label":"Bike share data tools and visualizations","href":"https://github.com/BetaNYC/Bike-Share-Data-Best-Practices/wiki/Bike-share-data-tools-and-visualizations","desc":"This is a listing of Bike Share data portals. It should list the city, link to the data system and outline the data currently provided.  There are also some data visualization options.",download:true,gis:false,explorer:true,chart:false,tools:false,resource:false},
{"topic":"military","label":"The Institute for Health Metrics and Evaluation","href":"http://www.healthdata.org/results/data-visualizations","desc":"The IHME is an independent global health research center at the University of Washington that provides rigorous and comparable measurement of the world's most important health problems and evaluates the strategies used to address them.","download":true,"gis":false,"explorer":true,"chart":true,"tools":false,"resource":false},
{"topic":"earth","label":"Global Surface Water Explorer","href":"https://global-surface-water.appspot.com/","desc":"The European Commission's Joint Research Centre developed this new water dataset in the framework of the Copernicus Programme. This maps the location and temporal distribution of water surfaces at the global scale over the past 32 years and provides statistics on the extent and change of those water surfaces. ","download":true,"gis":false,"explorer":true,"chart":true,"tools":false,"resource":false},
{"topic":"survey","label":"World Values Survey","href":"http://www.worldvaluessurvey.org/WVSOnline.jsp","desc":"\nThe World Values Survey (www.worldvaluessurvey.org) is a global network of social scientists studying changing values and their impact on social and political life, led by an international team of scholars, with the WVS association and secretariat headquartered in Stockholm, Sweden. ","download":true,"gis":true,"explorer":true,"chart":true,"tools":false,"resource":false},
{"topic":"energy","label":"Wind Europe","href":"https://windeurope.org/about-wind/statistics/","desc":"compare data across school districts","download":true,"gis":false,"explorer":false,"chart":true,"tools":false,"resource":false},","desc":"compare data across school districts","download":true,"gis":false,"explorer":false,"chart":true,"tools":false,"resource":false},
http://ec.europa.eu/energy/en
http://data.worldbank.org/
https://comtrade.un.org/data/
http://mo.ibrahim.foundation/iiag/downloads/
http://ec.europa.eu/eurostat
http://mo.ibrahim.foundation/iiag/downloads/
https://data.guttmacher.org/regions
http://datadryad.org/
https://www.gapminder.org/about-gapminder/
https://www.guttmacher.org/population-center/datasets
http://www.migrationpolicy.org/programs/migration-data-hub
http://www.epi.org/data/
http://www.earth-policy.org/data_center/
http://www.cbpp.org/research/housing/national-and-state-housing-fact-sheets-data
https://cepa.stanford.edu/seda/data-archive
http://www.commonwealthfund.org/interactives-and-data
http://www.annenbergpublicpolicycenter.org/tag/data-sets/
http://www.ppic.org/main/home.asp
https://www.cgdev.org/publication/dataset-vulnerability-climate-change
https://alpdata.rand.org/index.php?page=data
http://bruegel.org/publications/datasets/
http://civicyouth.org/ResearchTopics/research-products-cat/data-sets/

http://www.earthinstitute.columbia.edu/articles/view/1010
https://earth.esa.int/web/guest/home;jsessionid=DE7C6B460E5C0E3C786228F88DA0EA13.jvm2
World Resources- World Resources Institute
Hazardous Substance Release/Health Effects Database (HAZDAT) - Agency for Toxic Substances and Disease Registry
National Economic, Social, and Environmental Databank (Experimental) - Office of Business Analysis
Regional Economic Information System - U.S. Department of Commerce Bureau of Economic Analysis
Environmental Subset of Collection of Multilateral Conventions - Fletcher School, TUFTS University
UNCED Collection - United Nations Conference on Environment and Development
Register of International Treaties and Other Agreements in the Field of the Environment - United Nations Environment Programme
HIV/AIDS Surveillance Database - U.S. Census Bureau, Center for International Research
Polish General Social Survey 1992-93 - Institute for Social Studies, University of Warsaw
Georferenced Population Data of Mexico - Consortium for International Earth Science Information Network
IMAGE 2.0 - RIVM
International Data Base - U.S. Census Bureau, Center for International Research
Global Population Data Base - U.S. Census Bureau, Center for International Research
Caring for the Earth - World Conservation Union
IUCN Publications and Periodical Database - International Union for the Conservation of Nature
International Documentation Unit and Library of Indigenous Knowledge for Agriculture and Rural Development - Center for Indigenous Knowledge for Agriculture and Rural Development
Public Opinion Item Index - Institute for Research in Social Science
National Center for Geographic Information and Analysis
http://data.geocomm.com/

http://www.statemaster.com/index.php

http://www.dmlp.org/about-digital-media-law-project
https://data.cityofnewyork.us/Housing-Development/Building-Footprints/nqwf-w8eh
https://pitchinteractiveinc.github.io/tilegrams/
http://www.civicdata.io/dataset?res_format=CSV
https://trends.google.com/trends/
http://www1.nyc.gov/site/planning/data-maps/nyc-population.page 
https://rentlogic.com/#
https://github.com/fivethirtyeight/data
www.presidency.ucsb.edu/*
http://www.pogo.org/about/
http://www.foreffectivegov.org/
http://www.pogo.org/straus/revolving-door-database/revolving-door-database-coming-soon.html
http://ec.europa.eu/transparencyregister/public/homePage.do
http://nsarchive.gwu.edu/NSAEBB/
http://www.followthemoney.org/
http://www.start.umd.edu/gtd/


